import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import Nav from '@/components/nav';
import Footer from '@/components/footer';
import Copyright from '@/components/copyright';

const montserrat = Montserrat({ subsets: ['latin'] });

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} flex flex-col min-h-screen bg-grey max-w-[1214px] mx-auto px-4 overflow-x-hidden`}
      >
        <script id="ze-snippet" src="https://static.zdassets.com/ekr/snippet.js?key=3368f8dc-8a6f-4835-af8a-6348804be6bb"> </script>
        <Nav />
        {children}
        <Footer />
        <Copyright />
      </body>
    </html>
  );
}

export { metadata };
